apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swimlane

resources:
  - ../../base

images:
  - name: swimlane-devops-practical
    newName: swimlane-devops-practical
    newTag: local

patches:
  - path: patch-app-local.yaml
