apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swimlane

resources:
  - ../../base
  - ingress.yaml

images:
  - name: swimlane-devops-practical
    newName: ghcr.io/your-github-user/swimlane-devops-practical
    newTag: "1.0.0"

patches:
  - path: patch-app-production.yaml
