apiVersion: v1
kind: ConfigMap
metadata:
  name: swimlane-app-config
  labels:
    app.kubernetes.io/name: swimlane-devops-practical
    app.kubernetes.io/component: web
data:
  NODE_ENV: development
  PORT: "3000"
